spring:
  application:
    name: eureka-server
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
#    <!-- resolve protected mode issue(default=0.85) -->
#eureka:
#  server:
#    renewalPercentThreshold: 0.49

